### ISSUE TITLE
open selected links in tabs is not working on some pages

### ISSUE THREAD

**Issue by zevelorgani** [marcii/Linky-fork#1]
Warning: the example page is NSFW (full frontal nudity)
http://forum.oneclickchicks.com/showpost.php?p=2153564&postcount=66

Selecting the set of links on the left gives the following errors:

TypeError: opener.linkyShared is undefined
LinkySelect.prototype.updateInfo()
 select-links.js:51
LinkySelect.prototype.startup()
 select-links.js:397
onload()
 select-links.xul:1
LinkyContext.prototype.openLinks()
 main.js:410
LinkyContext.prototype.doLinks()
 main.js:448
oncommand()
 browser.xul:1
 select-links.js:51:2
TypeError: opener.linkyContext is undefined
LinkySelect.prototype.openLinks()
 select-links.js:351
oncommand()
 select-links.xul:1
LinkyContext.prototype.openLinks()
 main.js:410
LinkyContext.prototype.doLinks()
 main.js:448
oncommand()
 browser.xul:1
 select-links.js:351:5

**Comment by hensm** [comment]
Have you removed the original Linky addon?

**Comment by zevelorgani** [comment]
After I uninstalled and reinstalled several times, it started working.  Weird.
