### ISSUE TITLE
Thanks for the update, works perfectly. Wanted to ask you about an additional modification.

### ISSUE THREAD

**Issue by DamienRyan** [marcii/Linky-fork#2]
Hi, 

Thanks for this update, it's been very useful to me. I was wondering if it were possible to modify Linky so that it opens each link in a staggered manner, so that there is a 2-3 second delay between each link opening, rather than all at once. How much would you charge for such a change?

**Comment by hensm** [comment]
Sure, it's mostly working. I'll finish it up some time later today / tomorrow and upload a new version. 

I'm probably not going to add any other new features, though. The code is a huge mess, which I suppose isn't too unexpected given how old it is. I've been working on and off on a drop-in replacement for a while. It's just lacking in features at the moment.

**Comment by hensm** [comment]
https://github.com/marcii/Linky-fork/releases/tag/3.0.0.2

**Comment by hensm** [comment]
Just to add, I've also implemented this in the rewrite in a way that isn't a massive kludge. I'll probably release a beta version in the next few weeks depending on how much time I find to work on it.

**Comment by zevelorgani** [comment]
Please let us know when it is available

**Comment by hensm** [comment]
I haven't found as much time to work on it as I'd hoped I would. It's not really ready for a release. But, it sort of works if you don't care about anything beyond the most basic features (no settings, some broken/unimplemented features).

Here's the GitHub repo, anyway:
https://github.com/marcii/linkysdk

Feel free to create issues there for unimplemented/broken stuff or new features.

**Comment by hensm** [comment]
Starting experimenting with a webext version today:
![select](https://user-images.githubusercontent.com/6956633/28579311-34e44728-7154-11e7-867a-68704eafbff4.png)


No XUL, so it's not native-looking, unfortunately.
