### ISSUE TITLE
The add-on homepage points to the original add-on

### ISSUE THREAD

**Issue by zevelorgani** [marcii/Linky-fork#3]
The original Linky is dead and it's homepage hasn't been updated since 2005.
Please change the homepage reported to the add-on manager, as well as the "About" tab in the settings.

I understand the reason for keeping the donation link but people that use your fork should be able to easily reach it's web-site.

**Comment by hensm** [comment]
As I mentioned in another issue, I don't plan to update this any further. It'll break in release Firefox soon, anyway.
